name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/SSH_PRIVATE_KEY"
      - run: chmod 0600 "$HOME/.ssh/SSH_PRIVATE_KEY"
      - name: Install composer dependencies
        run: composer update
      - name: Build .env
        run: |
          touch .env
          echo APP_NAME=${{ secrets.MAIN_APP_NAME }} >> .env
          echo APP_ENV=${GITHUB_REF#refs/heads/} >> .env
          echo APP_KEY= >> .env
          echo APP_NAME=${{ secrets.MAIN_APP_NAME }} >> .env
          echo APP_URL=${{ secrets.MAIN_APP_URL }} >> .env
          echo DB_CONNECTION=${{ secrets.MAIN_DB_CONNECTION }} >> .env
          echo DB_HOST=${{ secrets.MAIN_DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.MAIN_DB_PORT }} >> .env
          echo DB_DATABASE=${{ secrets.MAIN_DB_DATABASE }} >> .env
          echo DB_USERNAME=${{ secrets.MAIN_DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.MAIN_DB_PASSWORD }} >> .env
      - name: Generate encryption key
        run: php artisan key:generate
      - name: Deploy
        run: rsync --exclude-from=rsync_exclude.txt --del -e "ssh -p ${{ secrets.MAIN_PORT }} -i $HOME/.ssh/SSH_PRIVATE_KEY -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.MAIN_USERNAME }}@${{ secrets.MAIN_HOST }}:${{ secrets.MAIN_DEPLOY_PATH }}
      - name: Run command
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.MAIN_USERNAME }}
          host: ${{ secrets.MAIN_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.MAIN_PORT }}
          script: "cd domains/maphr
          && ${{ secrets.MAIN_PHP_PATH }} artisan migrate:refresh --seed
          && ${{ secrets.MAIN_PHP_PATH }} artisan optimize:clear"
